services:
  - type: web
    name: eki-mvp
    runtime: python
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn mvp_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: DJANGO_SETTINGS_MODULE
        value: mvp_project.settings
      - key: DJANGO_DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: eki-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WHATSAPP_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_ID
        sync: false
      - key: WHATSAPP_VERIFY_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: eki-db
    plan: free
    databaseName: eki_mvp_db
    user: eki_user
